# Common definitions

LIBSDRT_SRC = $(wildcard $(LIBSDRT_ROOT)/src/d/rt/*.d)
LIBSDRT_OBJ = $(LIBSDRT_SRC:$(LIBSDRT_ROOT)/src/d/rt/%.d=obj32/rt/%.o)

LIBSDRT = lib/libsdrt32.a

ALL_TARGET ?= $(LIBSDRT)

LIBSDRT_IMPORTS = -I$(LIBSDRT_ROOT)/src

all: $(ALL_TARGET)

obj32/rt/%.o: $(LIBSDRT_ROOT)/src/d/rt/%.d $(LIBSDRT_SRC) $(LIBSDRT_EXTRA_DEPS)
	@mkdir -p obj32/rt
	$(SDC) -m32 -c -o $@ $< $(LIBSDRT_IMPORTS)

$(LIBSDRT): $(LIBSDRT_OBJ)
	@mkdir -p lib
	ar rcs $(LIBSDRT) $^

