language: d
#compiler:
# - dmd
install:

- sudo apt-get -y update || true
- sudo apt-get -fy install llvm-3.4 || true


script:
- dub fetch doveralls
- dub -b cov
- ./sdc --test
- COVERALLS_REPO_TOKEN=Tle1nyVNDhgDukE7V1r0hsMVRGDcKnRW0 dub run doveralls
