language: d
#compiler:
# - dmd
install:
# dmd
- DMD_VER=2.066.0
- DMD=dmd_${DMD_VER}-0_amd64.deb
- DUB_VER=0.9.22
- DUB=dub-${DUB_VER}-linux-x86_64
- wget http://downloads.dlang.org/releases/2014/${DMD}
- sudo dpkg -i ${DMD} || true
- sudo apt-get -y update || true
- sudo apt-get -fy install llvm-3.4 || true
- sudo dpkg -i ${DMD}


script:
- make LLVM_CONFIG=llvm-config-3.4
- dub
- cat bin/sdc.conf
- dmd tests/runner.d -oftests/runner
- cd tests
- bin/sdc -m32 -o test0001.bin test0001.d -Ilibs -Llibsdrt/lib
- ./test0001.bin
- echo $?
- ./runner

