language: d
#compiler:
# - dmd
install:
- DUB_VER=0.9.22
- DUB=dub-${DUB_VER}-linux-x86_64
- sudo dpkg -i ${DUB} || true
- sudo apt-get -y update || true
- sudo apt-get -fy install llvm-3.4 || true


script:
- dub fetch doveralls
- dub -b cov
- echo "{\"includePath\": [\"$(PWD)/libs\", \".\"],\"libPath\": [\"$(PWD)/lib\"],}" > ./sdc.conf
- ./sdc --test
- COVERALLS_REPO_TOKEN=Tle1nyVNDhgDukE7V1r0hsMVRGDcKnRW0 dub run doveralls
