# Common definitions

LIBSDC_SRC = \
	$(SDC_ROOT)/src/sdc/*.d \
	$(SDC_ROOT)/src/util/*.d

DRIVER_SRC = $(SDC_ROOT)/src/driver/*.d

SDC = bin/sdc

LIBSDC = lib/libsdc.a

ALL_TARGET ?= $(LIBSDC) $(SDC)

LIBD_LLVM_ROOT ?= $(SDC_ROOT)/../libd-llvm
ALL_TARGET ?= $(SDC) bin/sdc.conf

include $(LIBD_LLVM_ROOT)/makefile.common

SDC_IMPORTS = -I$(SDC_ROOT)/src $(LIBD_LLVM_IMPORTS) -I$(LIBD_LLVM_ROOT)/src

$(SDC): $(LIBSDC) $(LIBD) $(LIBD_LLVM)
	@mkdir -p bin
	$(DMD) -c -ofobj/driver.o $(DRIVER_SRC) $(DFLAGS) $(SDC_IMPORTS)
	gcc -o $(SDC) obj/driver.o $(ARCHFLAG) $(LDFLAGS)

$(LIBSDC): $(SDC_SRC) $(LIBD_DEP_BASE)
	@mkdir -p lib obj
	$(DMD) -c -ofobj/sdc.o $(LIBSDC_SRC) $(DFLAGS) $(SDC_IMPORTS)
	ar rcs $(LIBSDC) obj/sdc.o

bin/sdc.conf:
	@mkdir -p bin
	printf "{\n\t\"includePath\": [\"$(PWD)/phobos\", \".\"],\n\t\"libPath\": [\"$(PWD)/lib\"],\n}\n" > $@
